version: 0.2
env:
  variables:
    REPOSITORY_URI: naresh546
    DOCKERHUB_TOKEN: dckr_pat_e5UVxPAPz1V5s1dMthMIb6yZXgM
    DOCKERHUM_USER: naresh546
phases:
  pre_build:
    commands:
      #Docker Hub login
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUM_USER} --password-stdin
  build:
    commands:
      - echo "changing the directory"
      - ls
      - cd ECS
      - ls
      - docker context ls
#   post_build:
#     commands:
#       - echo "Taging Docker Images and pushing to ECR"
#       - docker tag blog-site-ui:latest ${ECR_IMAGE_URI}
#       - echo ${ECR_IMAGE_URI}
#       - docker push ${ECR_IMAGE_URI}
#       #Generatie image definitions file for ECS
#       - printf '[{"name":"blog-ui-container", "imageUri":"%s"}]' ${ECR_IMAGE_URI} > imagedefinitions.json
# artifacts:
#   files:
#     - imagedefinitions.json
#   discard-paths: yes
