version: 0.2
env:
  variables:
    REPOSITORY_URI: naresh546
    DOCKERHUB_TOKEN: dckr_pat_e5UVxPAPz1V5s1dMthMIb6yZXgM
    DOCKERHUM_USER: naresh546
phases:
  install:
    commands:
      - mv /usr/local/bin/docker /usr/bin/docker
      - curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh
  pre_build:
    commands:
      #Docker Hub login
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUM_USER} --password-stdin
  build:
    commands:
      - echo "changing the directory"
      - cd ECS
      - ls
      - docker context ls
      - echo "createing myecs context of type ecs"
      - docker context create ecs demoecs
      - echo "changing the context"
      - docker context use demoecs --from-env
      - echo "checking the selected context"
      - docker context ls
#   post_build:
#     commands:
#       - echo "Taging Docker Images and pushing to ECR"
#       - docker tag blog-site-ui:latest ${ECR_IMAGE_URI}
#       - echo ${ECR_IMAGE_URI}
#       - docker push ${ECR_IMAGE_URI}
#       #Generatie image definitions file for ECS
#       - printf '[{"name":"blog-ui-container", "imageUri":"%s"}]' ${ECR_IMAGE_URI} > imagedefinitions.json
# artifacts:
#   files:
#     - imagedefinitions.json
#   discard-paths: yes
