global: 
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'accounts'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['accounts:8081']
  - job_name: 'loans'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['loans:8083']
  - job_name: 'cards'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['cards:8082']
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['api-gateway:9000']
  - job_name: 'eurekaserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['eurekaserver:8761']
  - job_name: 'configserver'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['configserver:8100']
