version: "3.8"

services:

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.1.1
    environment: 
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks: 
      - logging-network

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.1.1
    depends_on: 
      - elasticsearch
    ports:
      - 12201:12201/udp
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro 
    networks:
      - logging-network

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.1.1
    depends_on:
      - logstash
    ports: 
      - 5601:5601
    networks: 
      - logging-network

  mongodb:
    container_name: mongodb
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - mongo-volume:/data/db
    networks:
     - blogsite
    logging:
      driver: gelf
      options:
        gelf-address: "udp://host.docker.internal:12201"



  database-mysql:
    image: mysql
    container_name: database-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogsite   
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
     - mysql-volume:/var/lib/mysql
    networks:
     - blogsite
    logging:
      driver: gelf
      options:
        gelf-address: "udp://host.docker.internal:12201"

  axonserver:
    container_name: axonserver
    image: axoniq/axonserver
    hostname: axonserver
    volumes:
      - axonserver-data:/data
      - axonserver-events:/eventdata
      - axonserver-config:/config:ro
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - blogsite
    logging:
      driver: gelf
      options:
        gelf-address: "udp://host.docker.internal:12201"

  eurekaserver:
    container_name: eurekaserver
    image: naresh546/blogsite-eurekaserver:latest 
    mem_limit: 700m
    ports:
      - "8761:8761"
    networks:
      - blogsite
    logging:
      driver: gelf
      options:
        gelf-address: "udp://host.docker.internal:12201"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev

  configserver:
    container_name: configserver
    image: naresh546/blogsite-config-server:latest
    mem_limit: 700m
    ports:
     - "8100:8100"
    networks:
     - blogsite
    logging:
      driver: gelf
      options:
        gelf-address: "udp://host.docker.internal:12201"
    depends_on:
     - eurekaserver
    environment:
      SPRING_PROFILES_ACTIVE: default
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/


  apigateway:
    container_name: apigateway
    image: naresh546/blogsite-apigateway:latest
    mem_limit: 700m
    ports:
     - "9000:9000"
    networks:
     - blogsite
    logging:
      driver: gelf
      options:
        gelf-address: "udp://host.docker.internal:12201"
    depends_on:
     - eurekaserver
    environment:
      SPRING_PROFILES_ACTIVE: dev
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/
      
  user:
    container_name: user
    image: naresh546/blogsite-user:latest
    mem_limit: 700m
    ports:
      - "8000:8000"
    networks:
      - blogsite
    logging:
      driver: gelf
      options:
        gelf-address: "udp://host.docker.internal:12201"
    depends_on:
      - configserver
      - database-mysql
      - axonserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      #SPRING_CONFIG_IMPORT: configserver:http://configserver:8100/
      AXON_AXONSERVER_SERVERS: axonserver:8124
      # EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: eurekaserver:8761/eureka/

  user-replica:
    container_name: user-replica
    image: naresh546/blogsite-user-replica:latest 
    mem_limit: 700m
    ports:
      - "8001:8001"
    networks:
      - blogsite
    logging:
      driver: gelf
      options:
        gelf-address: "udp://host.docker.internal:12201"
    depends_on:
      - configserver
      - axonserver
      - eurekaserver
      - mongodb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017
      #SPRING_CONFIG_IMPORT: configserver:http://configserver:8100/
      AXON_AXONSERVER_SERVERS: axonserver:8124
      # EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: eurekaserver:8761/eureka/

  blog:
    container_name: blog
    image: naresh546/blogsite-blog:latest
    mem_limit: 700m
    ports:
      - "8010:8010"
    networks:
      - blogsite
    logging:
      driver: gelf
      options:
        gelf-address: "udp://host.docker.internal:12201"
    depends_on:
      - configserver
      - database-mysql
      - axonserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      # SPRING_CONFIG_IMPORT: configserver:http://configserver:8100/
      # AXON_AXONSERVER_SERVERS: axonserver:8124
      # EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/


  blog-replica:
    container_name: blog-replica
    image: naresh546/blogsite-blog-replica:latest
    mem_limit: 700m
    ports:
      - "8011:8011"
    networks:
      - blogsite
    logging:
      driver: gelf
      options:
        gelf-address: "udp://host.docker.internal:12201"
    depends_on:
      - configserver
      - mongodb
      - axonserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 60s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017
      # SPRING_CONFIG_IMPORT: configserver:http://configserver:8100/
      # AXON_AXONSERVER_SERVERS: axonserver:8124
      # EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8761/eureka/










#volumes and networks
volumes:
  axonserver-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
  axonserver-events:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/events
      o: bind
  axonserver-config:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/config
      o: bind      
volumes:
  mysql-volume:
  axonserver-data:
  axonserver-events:
  axonserver-config:
  mongo-volume:
networks:
  blogsite:
  logging-network:
    driver: bridge